env: standard
runtime: nodejs16
service: search-now
instance_class: F2

handlers:
  - url: /employersearch.*
    script: auto
    secure: always
    redirect_http_response_code: 301

env_variables:
  ARGYLE_API_KEY: $ARGYLE_API_KEY
  ARGYLE_API_SECRET: $ARGYLE_API_SECRET
  NEXT_PUBLIC_ARGYLE_BASE_URL: $NEXT_PUBLIC_ARGYLE_BASE_URL
  NEXT_PUBLIC_ARGYLE_LINK_KEY: $NEXT_PUBLIC_ARGYLE_LINK_KEY
  NEXT_PUBLIC_URL_PREFIX: $NEXT_PUBLIC_URL_PREFIX

default_expiration: "5m"
